// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9oHlrQdAyLVtpRFUsqwTsh3wN5C8bP4',
    appId: '1:3349637649:web:b0960b5327211ba0189fb0',
    messagingSenderId: '3349637649',
    projectId: 'mylucky-6bb16',
    authDomain: 'mylucky-6bb16.firebaseapp.com',
    storageBucket: 'mylucky-6bb16.firebasestorage.app',
    measurementId: 'G-LVK2FDDV9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDnE4biyuoeZydsK37PjYinGnP1TS8Afg',
    appId: '1:3349637649:android:5c3e0fdadd363251189fb0',
    messagingSenderId: '3349637649',
    projectId: 'mylucky-6bb16',
    storageBucket: 'mylucky-6bb16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbwNz5YGV6UZf6bDiOUYIROOgbjT44pXU',
    appId: '1:3349637649:ios:7c1d38905eafb254189fb0',
    messagingSenderId: '3349637649',
    projectId: 'mylucky-6bb16',
    storageBucket: 'mylucky-6bb16.firebasestorage.app',
    iosBundleId: 'com.example.mylucky.mylucky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbwNz5YGV6UZf6bDiOUYIROOgbjT44pXU',
    appId: '1:3349637649:ios:7c1d38905eafb254189fb0',
    messagingSenderId: '3349637649',
    projectId: 'mylucky-6bb16',
    storageBucket: 'mylucky-6bb16.firebasestorage.app',
    iosBundleId: 'com.example.mylucky.mylucky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu9oHlrQdAyLVtpRFUsqwTsh3wN5C8bP4',
    appId: '1:3349637649:web:64ba17d9bbcdae91189fb0',
    messagingSenderId: '3349637649',
    projectId: 'mylucky-6bb16',
    authDomain: 'mylucky-6bb16.firebaseapp.com',
    storageBucket: 'mylucky-6bb16.firebasestorage.app',
    measurementId: 'G-XC8T4MZTCR',
  );
}
